title: Crafting Supply Hub
email: craftingsupplyca@gmail.com
description: >-
  Welcome to Crafting Supply Hub , your go-to guide for Canadian crafting supplies, budget-friendly DIYs, and wholesale sourcing tips.
baseurl: ""
url: "https://craftingsupply.ca"

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Appearance & Localization
minimal_mistakes_skin: "default"
locale: "en-US"

# Author Info
author:
  name: "Crafting Supply Hub Team"
  bio: "Where creativity meets supplies."
  location: "Canada"

# Social Media
social:
  name: Crafting Supply Hub
  links:
    - https://craftingsupply.ca

# Footer
footer:
  links:
    - label: "About Us"
      url: "/about/"
    - label: "Contact Us"
      url: "/contact/"
  text: "© 2025 Crafting Supply Hub. Made with ❤️ in Canada."

# Include folders
include:
  - _pages
  - search.json

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .trash/

# Defaults for sidebar usage
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      sidebar:
        nav: "side"
